### ISSUE TITLE
Article Pages - Share This Article box overlaps Register Now form

### ISSUE THREAD

**Issue by davidmacp** [dadi/cloud#107]
### Expected behavior
On an article page user should be able to click on `Share this article` button and be presented with options to share via social media.

### Actual behavior
Depending on the length of the articles it appears that the `Share this article` button is near the bottom of the page it can overlap with the `Register now` form and the links cannot be clicked.

### Steps to reproduce the problem
Navigate to an article page
http://35.178.60.215/en/updates/website/introducing-the-new-website
Scroll down to bottom of article and click on the `Share this article` button
Share options overlap the `Register now` form and cannot be clicked.

![screen shot 2018-05-21 at 2 25 53 pm](https://user-images.githubusercontent.com/36462430/40290843-4f34f1ee-5d04-11e8-9f9c-78c9d7929bb9.png)

## Your Environment

* Version used: http://35.178.60.215/en
* Browser Name and version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac OSX

**Comment by abovedave** [comment]
This should sit over the top of the new related articles strip, can you retest please @davidmacp? Close if happy 📪

**Comment by davidmacp** [comment]
Looks good. Can still access the article link on the box underneath as well 👍 


![screen shot 2018-07-18 at 8 39 35 am](https://user-images.githubusercontent.com/36462430/42849394-5c6a1490-8a66-11e8-8d17-612c3d1733cd.png)


![screen shot 2018-07-18 at 8 39 04 am](https://user-images.githubusercontent.com/36462430/42849399-6663d1ca-8a66-11e8-8410-3c8f55b01568.png)
