### ISSUE TITLE
Sub-category pages e.g., /knowledge/network

### ISSUE THREAD

**Issue by abovedave** [dadi/cloud#119]

**Comment by abovedave** [comment]
Have added to beta site @davidmacp, can you check other pages on the site resolve correctly please?The routing was a bit of a chore

**Comment by davidmacp** [comment]
@abovedave 

Have checked the following combinations of categories and sub-categories as per my understanding:

/en/knowledge/web-services
/en/knowledge/announcements
/en/knowledge/network
/en/knowledge/website

/en/updates/web-services
/en/updates/announcements
/en/updates/network
/en/updates/website

/en/tutorials/web-services
/en/tutorials/announcements
/en/tutorials/network
/en/tutorials/website

All resolve to a page - no `404`'s
