### ISSUE TITLE
Change default sort order on articles collection

### ISSUE THREAD

**Issue by abovedave** [dadi/cloud#133]
Is it possible to sort by published `publishedAt: desc` by default?

**Comment by abovedave** [comment]
This didn't seem to work @jimlambie https://github.com/dadi/cloud/commit/a3dbaa2a7fc76334c99a0432e94397151a5118f5. Any ideas?

**Comment by jimlambie** [comment]
@abovedave this looks like it's impossible with the current build of Publish. It appears as if either the default field is `createdAt`, OR no sort field/order is passed to the DocumentList component until a column header sorting arrow is clicked. 

Another issue for the Publish board, please.

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#14

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#16

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#19
