### ISSUE TITLE
Implement semantic versioning

### ISSUE THREAD

**Issue by jimlambie** [dadi/cloud#134]
Along with information about the stack being used, could we show the current commit info somewhere, such as the footer, or even just in the source code?

using for example: https://www.npmjs.com/package/git-rev-sync

```
console.log(git.short());
// 75bf4ee
 
console.log(git.long());
// 75bf4eea9aa1a7fd6505d0d0aa43105feafa92ef
 
console.log(git.branch());
// master
```

Or, as an alternative, use the package.version value from Web, ensuring we update it for each deployment

**Comment by abovedave** [comment]
Use github's release rss feed for this footer?

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#15
