### ISSUE TITLE
Design for displaying agency partners

### ISSUE THREAD

**Issue by jobiddulph** [dadi/cloud#198]
### We need a design to display agency partners on dadi.cloud. Similarly to how AWS enable you to search for a partner:
https://aws.amazon.com/partners/find/
https://aws.amazon.com/partners/find/results/?keyword=dadi

We need to be able to display the name of partners on our site. We will only do this once we have a minimum number of partners signed up (e.g. 10)

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#4
