### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by abovedave** [dadi/cloud#8]
For after relaunch, data structure should allow this easily

https://github.com/dadi/api/issues/433
https://github.com/dadi/web/issues/405

**Comment by abovedave** [comment]
NB. Navigation update to allow to change languages

**Comment by jimlambie** [comment]
@paulrgn Can we have the list of required languages?

**Comment by jimlambie** [comment]
This issue was moved to dadi/cloud-issues#20
